WebApplication1/ViewModels/CarListViewModel.cs
using WebApplication1.Data.Models;

namespace WebApplication1.ViewModels
{
    public class CarListViewModel
    {
        public IEnumerable<Car> allCars { get; set; }

        public string currCategory { get; set;}

    }
}
 

WebApplication1/ViewModels/HomeViewModel.cs
using WebApplication1.Data.Models;

namespace WebApplication1.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> favCars { get; set; }
    }
}

WebApplication1/ViewModels/ShopCartViewModel.cs
using WebApplication1.Data.Models;

namespace WebApplication1.ViewModels
{
    public class ShopCartViewModel
    {

        public ShopCart shopCart { get; set; }


    }
}

WebApplication1/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data.Interaces;
using WebApplication1.Data.Models;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class CarsController : Controller
    {
        private readonly IAllCars _allCars;
        private readonly ICarsCategory _allCategories;

        public CarsController(IAllCars allCars, ICarsCategory allCategories)
        {
            _allCars = allCars;
            _allCategories = allCategories;
        }

        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        [Route("Cars/List/{category}/{id}")]
        public ViewResult List(string category) {

            var _categories = category;

            IEnumerable<Car> Cars = null;

            string currCategory;

            if (string.IsNullOrEmpty(category))
                Cars = _allCars.Cars.OrderBy(c => c.Id);
            else {
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                    Cars = _allCars.Cars.Where(c => c.Category.CategoryName.Equals("Електромобілі")).OrderBy(c => c.Id);
                else if (string.Equals("auto", category, StringComparison.OrdinalIgnoreCase))
                    Cars = _allCars.Cars.Where(c => c.Category.CategoryName.Equals("Легкові авто")).OrderBy(c => c.Id);
                else if (string.Equals("trucks", category, StringComparison.OrdinalIgnoreCase))
                    Cars = _allCars.Cars.Where(c => c.Category.CategoryName.Equals("Вантажні авто")).OrderBy(c => c.Id);
                else if (string.Equals("europlates", category, StringComparison.OrdinalIgnoreCase))
                    Cars = _allCars.Cars.Where(c => c.Category.CategoryName.Equals("Нерозмитнені авто")).OrderBy(c => c.Id);

                currCategory = _categories; 
            }

            var carObj = new CarListViewModel
            {
                allCars = Cars,
                currCategory = category
            };

            return View(carObj);
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data.Interaces;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {

        private readonly IAllCars _carRep;

        public HomeController(IAllCars carRepository)
        {

            _carRep = carRepository;
           
        }

        public ViewResult Index() {
            var homeCars = new HomeViewModel
            {
                favCars = _carRep.GetFavCars
            };
            return View(homeCars);
        }
    }
}

WebApplication1/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data.Interaces;
using WebApplication1.Data.Models;

namespace WebApplication1.Controllers
{
    public class OrderController : Controller
    {

        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }


        [HttpPost]
        public IActionResult CheckOut(Order order) {
            int i = 0;

            shopCart.ListShopItems = shopCart.GetShopItems();

            if (shopCart.ListShopItems.Count == 0)
            {
                ModelState.AddModelError("", "You may have items in the cart");
            }


            if (ModelState.ErrorCount-1 == 0)
            {
                allOrders.CreateOrder(order);
                return RedirectToAction("Index");
            }

            return View(order);
        }
        
        public IActionResult Checkout()
        {
            return View();
        }

        public IActionResult Index()
        {
            ViewBag.Message = "We got your order, we'll call you later";
            return View();
        }


    }
}

WebApplication1/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data.Interaces;
using WebApplication1.Data.Models;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class ShopCartController : Controller
    {

        private readonly IAllCars _carRep;

        private readonly ShopCart _shopCart;

        public ShopCartController(IAllCars carRepository, ShopCart shopCart) {
            
            _carRep = carRepository;
            _shopCart = shopCart;
        }

        public ViewResult Index() { 
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;

            var obj = new ShopCartViewModel {
                shopCart = _shopCart
            };

            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _carRep.Cars.FirstOrDefault(x => x.Id == id);

            if (item != null) {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction("Index");
        }

    }
}

WebApplication1/Views/Cars/List.cshtml
<h2>@Model.currCategory</h2>

<div class="row">
@{
	foreach (Car car in Model.allCars)
	{
		@Html.Partial("AllCars", car)
	}
}
</div>

WebApplication1/Views/Home/Index.cshtml
@model HomeViewModel

<h2>Favourite cars</h2>

<div class="row">
@{
	foreach (Car car in Model.favCars)
	{
		@Html.Partial("AllCars", car)
	}
}
</div>

WebApplication1/Views/Order/Checkout.cshtml
@model Order

<div class="row">
	<h3>Оформлення замовлення</h3>
	<form asp-action="Checkout" method="post" class="form-horizontal">
		<div class="form-group">
			<label asp-for="Name"></label>
			<div class="col-md-5">
				<input asp-for="Name" class="form-control"/>
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Surname"></label>
			<div class="col-md-5">
				<input asp-for="Surname" class="form-control"/>
				<span asp-validation-for="Surname" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Addres"></label>
			<div class="col-md-5">
				<input asp-for="Addres" class="form-control"/>
				<span asp-validation-for="Addres" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Phone"></label>
			<div class="col-md-5">
				<input asp-for="Phone" class="form-control"/>
				<span asp-validation-for="Phone" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Email"></label>
			<div class="col-md-5">
				<input asp-for="Email" class="form-control"/>
				<span asp-validation-for="Email" class="text-danger"></span>
			</div>
		</div>
		<input class="btn btn-success" type="submit" action="Checkout" value="Order"/>
	</form>
</div>

WebApplication1/Views/Order/Index.cshtml
<h3>@ViewBag.Message</h3>

WebApplication1/Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4">
	<img class="img-thumbnail" src="@Model.Img" ></img>
	<h5>@Model.Name</h5>
	<p>Price: @Model.Price.ToString("c")</p>
	<p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.Id">Add to cart</a></p>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
@{
    string pathToIcons = "/icons/bootstrap-icons.svg";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link href="~/css/style.css" rel="stylesheet" type="text/css"/>
    
</head>
<body>

    <header>
    <div class="px-3 py-2 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <img class="bi me-2" width="60" alt="Label" src="~/img/mainPic.png"/>
          </a>

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="/Cars/List" class="nav-link text-secondary">
                <img class="bi d-block mx-auto mb-1" width="24" height="24" src="~/img/car.png" />
                All cars
              </a>
            </li> 
            <li>
              <a href="/Cars/List/electro" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24" fill="white"><use xlink:href="@pathToIcons#lightning-charge-fill"></use></svg>
                Electro
              </a>
            </li>
            <li>
              <a href="/Cars/List/auto" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24" fill="white"><use xlink:href="@pathToIcons#table"></use></svg>
                Cars
              </a>
            </li>
            <li>
                <a href="/Cars/List/trucks" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24" fill="white"><use xlink:href="@pathToIcons#truck"></use></svg>
                Trucks
              </a>
              
            </li>
            <li>
                <a href="/Cars/List/europlates" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24" fill="white"><use xlink:href="@pathToIcons#currency-euro"></use></svg>
                Europеan
              </a>
              
            </li>
            <li>
              <a href="/ShopCart/Index" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24" fill="white"><use xlink:href="@pathToIcons#cart"></use></svg>
                Cart
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="px-3 py-2 border-bottom mb-3">
      <div class="container d-flex flex-wrap justify-content-center">
        <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto" role="search">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-light text-dark me-2">Login</button>
          <button type="button" class="btn btn-primary">Sign-up</button>
        </div>
      </div>
    </div>
  </header>

    <div class="container">
        @RenderBody()
    </div>

    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <img class="bi me-2" width="50" alt="Label" src="~/img/mainPic2.png"/>
          </a>
          <span class="mb-3 mb-md-0 text-muted">© 2022 Company, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="@pathToIcons#twitter"></use></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="@pathToIcons#instagram"></use></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="@pathToIcons#facebook"></use></svg></a></li>
        </ul>
        </footer>
    </div>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

WebApplication1/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class="container">
	@{
		foreach (var elem in Model.shopCart.ListShopItems)
		{
			<div class="alert alert-primary">
				<b>Automobile: </b> @elem.Car.Name <br/>
				<b>Price: </b> @elem.Car.Price.ToString("c")
			</div>
		}
	}
	<hr/>

	<a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Order</a>
</div>